-- This is an attempt at scheduling a main loop using coroutines but its not working yet

-- local function noop()
-- 	print("no loop")
-- end
-- local function main_loop()
-- 	local user_main_loop = User_main_loop or noop
-- 	print("Start waiting...")
-- 	tools.wait(3) -- Wait for 3 seconds
-- 	print("Finished waiting!")
-- 	while true do
-- 		user_main_loop() -- Call the user-defined main loop function
-- 		tools.wait(1) -- Wait for 1 second before the next iteration
-- 	end
-- end

-- local co = coroutine.create(main_loop)
--
-- -- Scheduler to resume the coroutine
-- while coroutine.status(co) ~= "dead" do
-- 	coroutine.resume(co)
-- end
